"""Pytest fixtures and helpers for testing Makefile behavior and macros."""

from __future__ import annotations

import os
import subprocess
from pathlib import Path
from typing import Any

import pytest


@pytest.fixture
def temp_makefile_dir(tmp_path: Path) -> Path:
    """Provide an isolated directory for writing test Makefiles."""
    return tmp_path / "make-test"
    # The caller should mkdir if needed, or we can do it here.


def write_makefile(base_dir: Path, content: str, filename: str = "Makefile") -> Path:
    """Write a Makefile (or .mk include) into the given directory and return its path."""
    base_dir.mkdir(parents=True, exist_ok=True)
    makefile_path = base_dir / filename
    makefile_path.write_text(content)
    return makefile_path


# Exact copies of the critical macros from the real Makefile (as of the time of writing).
# These are intentionally duplicated here so the macro tests are self-contained
# and do not depend on the real Makefile changing under them.
HOST_ONLY_GUARD = r'''
define HOST_ONLY_GUARD
	@if [ -n "$$REMOTE_CONTAINERS" ] || [ -n "$$CODESPACES" ] || \
	    [ "$$XG_AIS_HOST_TYPE" = "xgic-devcontainer" ]; then \
		echo "❌ This command must be run from the host, not inside the Dev Container."; \
		exit 1; \
	fi
endef
'''

RUN_IN_CONTAINER = r'''
define RUN_IN_CONTAINER
	@if [ -z "$$REMOTE_CONTAINERS" ] && [ -z "$$CODESPACES" ] && \
	    [ "$$XG_AIS_HOST_TYPE" != "xgic-devcontainer" ]; then \
		echo "→ Running '$@' inside the dev container..."; \
		$(DOCKER_COMPOSE) exec --user node $(SERVICE_NAME) $(1) || { \
			echo ""; \
			echo "❌ Failed to run '$@' inside the dev container."; \
			echo "   Is the container running? Try:  make up"; \
			echo "   Or use: VS Code → Dev Containers: Reopen in Container"; \
			exit 1; \
		}; \
	else \
		$(1); \
	fi
endef
'''


@pytest.fixture
def minimal_makefile_with_macros(temp_makefile_dir: Path) -> Path:
    """
    Write a minimal self-contained Makefile that includes the two critical
    guard macros + a few exercise targets. Used for precise macro behavior tests.
    """
    makefile_dir = temp_makefile_dir
    makefile_dir.mkdir(parents=True, exist_ok=True)

    content = f'''# Minimal test harness for the key Makefile macros
# This file is generated by tests and is not committed.

COMPOSE_FILE       ?= docker-compose.yml
PROJECT_NAME       ?= test-project
SERVICE_NAME       ?= test-service
DOCKER_COMPOSE     := docker compose -f $(COMPOSE_FILE) -p $(PROJECT_NAME)

{HOST_ONLY_GUARD}

{RUN_IN_CONTAINER}

# Simple targets that exercise the macros (these are what we actually invoke in tests)
.PHONY: host-only-target
host-only-target:
\t$(HOST_ONLY_GUARD)
\t@echo "HOST_ONLY_TARGET_RAN_SUCCESSFULLY"

.PHONY: container-aware-target
container-aware-target:
\t$(call RUN_IN_CONTAINER, echo "CONTAINER_AWARE_RAN:inside_or_delegated")
\t@echo "CONTAINER_AWARE_TARGET_FINISHED"

# Target that deliberately passes a command with a leading @ (simulates the bug pattern)
.PHONY: dangerous-at-target
dangerous-at-target:
\t$(call RUN_IN_CONTAINER, @echo "THIS_SHOULD_NEVER_BE_SEEN_WITH_LEADING_AT")
\t@echo "DANGEROUS_TARGET_FINISHED"

# A target that records exactly what was "executed" via a fake side-effect file
# Useful for asserting the precise string that reached the docker layer.
.PHONY: record-delegated-command
record-delegated-command:
\t$(call RUN_IN_CONTAINER, @sh -c 'printf "%s" "$(1)" > /tmp/delegated_cmd.txt')
'''

    return write_makefile(makefile_dir, content)


@pytest.fixture
def real_makefile_path() -> Path:
    """Return the path to the real project Makefile (for higher-level smoke tests)."""
    # Assumes tests are run from repo root
    return Path(__file__).parents[2] / "Makefile"


# Helper to run make with a completely controlled environment
def run_make(
    makefile_dir: Path,
    target: str,
    env: dict[str, str] | None = None,
    extra_args: list[str] | None = None,
    check: bool = False,
) -> subprocess.CompletedProcess[str]:
    """
    Run `make` in the given directory with a controlled environment.
    Returns the CompletedProcess so tests can inspect stdout/stderr/returncode.
    """
    env = env or {}
    full_env = os.environ.copy()
    # Strip any real container markers so tests start from a known "host" baseline
    for key in ("REMOTE_CONTAINERS", "CODESPACES", "XG_AIS_HOST_TYPE"):
        full_env.pop(key, None)
    full_env.update(env)

    cmd = ["make", "-C", str(makefile_dir), "-f", "Makefile", target]
    if extra_args:
        cmd.extend(extra_args)

    return subprocess.run(
        cmd,
        env=full_env,
        capture_output=True,
        text=True,
        check=check,
    )
