blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/xgic/payload-cms-dev-containers/blob/main/CONTRIBUTING.md
    about: Please read our contribution guidelines before opening an issue.
  - name: Discussions
    url: https://github.com/xgic/payload-cms-dev-containers/discussions
    about: Ask questions and share ideas here (not for bugs or tracked feature work).
