#!/usr/bin/env bash
# Idempotent, host-conditional Git DX for Dev Containers.
# - Git safe.directory only when FS / hint says it is needed
# - Optional Docker Desktop SSH agent sock export when present
# Does not bake private keys or set safe.directory '*'.
#
# Intended to run once per container start from Docker Compose
# (primary service command), not from devcontainer.json lifecycle hooks.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOGGING_LIB="${SCRIPT_DIR}/lib/logging.sh"
HOST_FS_LIB="${SCRIPT_DIR}/lib/host-fs.sh"

if [ -f "$LOGGING_LIB" ]; then
  # shellcheck source=lib/logging.sh
  source "$LOGGING_LIB"
else
  log_info() { echo "[$1] $2"; }
  log_success() { echo "[$1] $2"; }
  log_warn() { echo "[$1] $2" >&2; }
  log_error() { echo "[$1] $2" >&2; }
  log_debug() { :; }
fi

# shellcheck source=lib/host-fs.sh
source "$HOST_FS_LIB"

PREFIX="git-dx"
DRY_RUN=0
STATUS_ONLY=0
# Quiet by default when invoked from Compose. Verbose for --status or
# XGIC_GIT_DX_VERBOSE=1 / --verbose.
QUIET=1
if [ "${XGIC_GIT_DX_VERBOSE:-0}" = "1" ]; then
  QUIET=0
fi

usage() {
  cat <<'EOF'
Usage: configure-git-dx.sh [--status] [--dry-run] [--verbose] [--quiet] [--help]

Host-conditional Git DX (safe.directory + SSH agent hints).

  --status    Print detection results; make no changes (implies verbose)
  --dry-run   Show actions without applying them
  --verbose   Log detection status even when no changes are needed
  --quiet     Only log when applying a change or warning (default)
  --help      Show this help

Env:
  XGIC_WORKSPACE          Workspace path (default: /workspace)
  XGIC_DOCKER_HOST_OS     Optional hint: windows|linux|macos
  XGIC_DD_SSH_AUTH_SOCK   Docker Desktop SSH sock path override
  XGIC_PROC_MOUNTS        Override /proc/mounts (tests)
  XGIC_GIT_DX_VERBOSE=1   Same as --verbose
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --status)
      STATUS_ONLY=1
      QUIET=0
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --verbose)
      QUIET=0
      shift
      ;;
    --quiet)
      QUIET=1
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      log_error "$PREFIX" "Unknown option: $1"
      usage >&2
      exit 2
      ;;
  esac
done

ws="$(xgic_workspace_path)"
hint="$(xgic_docker_host_os_hint)"
fstype="$(xgic_workspace_fstype || true)"
needs_safe=0
needs_dd_ssh=0
if xgic_needs_git_safe_directory; then
  needs_safe=1
fi
if xgic_needs_dd_ssh_agent_hint; then
  needs_dd_ssh=1
fi

vlog_info() {
  if [ "$QUIET" -eq 0 ]; then
    log_info "$PREFIX" "$1"
  fi
}

print_status() {
  vlog_info "workspace=${ws}"
  vlog_info "fstype=${fstype:-unknown}"
  vlog_info "XGIC_DOCKER_HOST_OS=${hint:-unset}"
  vlog_info "needs_safe_directory=${needs_safe}"
  vlog_info "needs_dd_ssh_hint=${needs_dd_ssh}"
  if xgic_dd_ssh_auth_sock_present; then
    vlog_info "dd_ssh_sock=present ($(xgic_dd_ssh_auth_sock))"
  else
    vlog_info "dd_ssh_sock=absent"
  fi
  if [ -n "${SSH_AUTH_SOCK:-}" ]; then
    vlog_info "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}"
  else
    vlog_info "SSH_AUTH_SOCK=unset"
  fi
}

safe_directory_configured() {
  local entry
  entry="$(git config --global --get-all safe.directory 2>/dev/null || true)"
  printf '%s\n' "$entry" | grep -qx "$ws"
}

configure_safe_directory() {
  if safe_directory_configured; then
    log_debug "$PREFIX" "safe.directory already includes ${ws}"
    return 0
  fi
  if [ "$DRY_RUN" -eq 1 ]; then
    log_info "$PREFIX" \
      "dry-run: git config --global --add safe.directory ${ws}"
    return 0
  fi
  git config --global --add safe.directory "$ws"
  log_success "$PREFIX" "Added safe.directory ${ws}"
}

bashrc_snippet_path() {
  printf '%s\n' "${HOME}/.config/xgic/git-dx-ssh.sh"
}

# Persist SSH_AUTH_SOCK for interactive shells when DD sock is mounted.
install_ssh_bashrc_snippet() {
  local sock snippet marker rc
  sock="$(xgic_dd_ssh_auth_sock)"
  snippet="$(bashrc_snippet_path)"
  marker="# XGIC git-dx SSH agent (managed)"
  rc="${HOME}/.bashrc"

  if [ "$DRY_RUN" -eq 1 ]; then
    log_info "$PREFIX" \
      "dry-run: write ${snippet} and source from ~/.bashrc"
    return 0
  fi

  mkdir -p "$(dirname "$snippet")"
  cat >"$snippet" <<EOF
# Generated by configure-git-dx.sh — do not store secrets here.
${marker}
_xgic_dd_sock='${sock}'
if [ -S "\${_xgic_dd_sock}" ]; then
  export SSH_AUTH_SOCK="\${_xgic_dd_sock}"
fi
unset _xgic_dd_sock
EOF

  touch "$rc"
  if ! grep -Fq "$snippet" "$rc" 2>/dev/null; then
    {
      printf '\n%s\n' "$marker"
      printf '[ -f "%s" ] && . "%s"\n' "$snippet" "$snippet"
    } >>"$rc"
  fi

  if [ -S "$sock" ]; then
    export SSH_AUTH_SOCK="$sock"
  fi
  log_success "$PREFIX" "SSH agent snippet ready (${sock})"
}

print_ssh_guidance() {
  if [ -n "${SSH_AUTH_SOCK:-}" ] && [ -S "${SSH_AUTH_SOCK}" ]; then
    vlog_info "SSH agent socket already available"
    return 0
  fi
  if xgic_dd_ssh_auth_sock_present; then
    install_ssh_bashrc_snippet
    return 0
  fi
  if [ "$needs_dd_ssh" -eq 1 ]; then
    # Warnings stay visible even in quiet mode (Compose logs only).
    log_warn "$PREFIX" \
      "Docker Desktop SSH sock not mounted. Opt in with Compose fragment:"
    log_warn "$PREFIX" \
      "  .devcontainer/docker-compose.git-dx.yml"
    log_warn "$PREFIX" \
      "Or prefer HTTPS + VS Code Git credential helper."
    return 0
  fi
  log_debug "$PREFIX" \
    "Linux hosts: VS Code usually forwards SSH_AUTH_SOCK; no change"
}

print_status

if [ "$STATUS_ONLY" -eq 1 ]; then
  exit 0
fi

if [ "$needs_safe" -eq 1 ]; then
  configure_safe_directory
else
  vlog_info "Skipping safe.directory (not needed on this mount)"
fi

print_ssh_guidance

exit 0
