#!/usr/bin/env python3
"""Optional advanced helper: generate docker-compose.agent.yml from host capabilities.

**Not used by default Dev Container reopen.** ``devcontainer.json`` has no
``initializeCommand``; Git DX runs from Docker Compose + ``configure-git-dx.sh``.

Keep this script for operators who want an opt-in SSH agent overlay. Prefer
HTTPS + VS Code host credential helper for github.com.
"""

from __future__ import annotations

import json
import os
import platform
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
DEVCONTAINER_DIR = SCRIPT_DIR.parent
OUT_FILE = DEVCONTAINER_DIR / "docker-compose.agent.yml"
SERVICE = os.environ.get("XGIC_COMPOSE_PRIMARY_SERVICE", "xgic-payload-cms-dev")
DD_SOCK = "/run/host-services/ssh-auth.sock"


def _run(cmd: list[str], timeout: float = 20.0) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        cmd,
        check=False,
        capture_output=True,
        text=True,
        timeout=timeout,
    )


def detect_host_os() -> str:
    explicit = (os.environ.get("XGIC_DOCKER_HOST_OS") or "").strip().lower()
    if explicit in {"windows", "linux", "macos", "darwin"}:
        return "macos" if explicit == "darwin" else explicit
    sysname = platform.system().lower()
    if sysname == "windows":
        return "windows"
    if sysname == "darwin":
        return "macos"
    return "linux"


def detect_docker_kind() -> str:
    """Return desktop | engine | unknown using ``docker info``."""
    try:
        proc = _run(["docker", "info", "-f", "{{json .}}"])
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return "unknown"
    if proc.returncode != 0 or not proc.stdout.strip():
        return "unknown"
    try:
        info = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return "unknown"
    operating = str(info.get("OperatingSystem") or "")
    name = str(info.get("Name") or "")
    blob = f"{operating} {name}".lower()
    if "desktop" in blob:
        return "desktop"
    return "engine"


def dd_ssh_sock_is_socket() -> bool:
    """True when Docker Desktop host-services SSH sock exists as a socket."""
    try:
        proc = _run(
            [
                "docker",
                "run",
                "--rm",
                "-v",
                f"{DD_SOCK}:{DD_SOCK}",
                "alpine:3.20",
                "sh",
                "-c",
                f'if [ -S "{DD_SOCK}" ]; then echo SOCKET; else echo NO; fi',
            ],
            timeout=60.0,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired, OSError):
        return False
    return proc.returncode == 0 and "SOCKET" in (proc.stdout or "")


def host_ssh_auth_sock() -> str | None:
    sock = (os.environ.get("SSH_AUTH_SOCK") or "").strip()
    if not sock:
        return None
    if platform.system().lower() == "windows":
        return None
    if not os.path.exists(sock):
        return None
    return sock


def render_overlay(
    *,
    host_os: str,
    kind: str,
    mode: str,
    ssh_auth_sock_env: str | None,
    mount_dd: bool,
    mount_host_sock: str | None,
) -> str:
    lines = [
        "# AUTO-GENERATED by prepare_host_git_compose.py — optional advanced use.",
        "# Not wired into default reopen (no initializeCommand).",
        f"# host_os={host_os} docker_kind={kind} git_auth_mode={mode}",
        "services:",
        f"  {SERVICE}:",
        "    environment:",
        f"      XGIC_DOCKER_HOST_OS: {host_os}",
        f"      XGIC_DOCKER_HOST_KIND: {kind}",
        f"      XGIC_GIT_AUTH_MODE: {mode}",
    ]
    if ssh_auth_sock_env:
        lines.append(f"      SSH_AUTH_SOCK: {ssh_auth_sock_env}")

    volume_lines: list[str] = []
    if mount_dd:
        volume_lines.extend(
            [
                "      - type: bind",
                f"        source: {DD_SOCK}",
                f"        target: {DD_SOCK}",
            ]
        )
    if mount_host_sock:
        volume_lines.extend(
            [
                "      - type: bind",
                f"        source: {mount_host_sock}",
                "        target: /ssh-agent",
            ]
        )

    if volume_lines:
        lines.append("    volumes:")
        lines.extend(volume_lines)

    lines.append("")
    return "\n".join(lines)


def decide() -> tuple[str, str, str, str | None, bool, str | None]:
    host_os = detect_host_os()
    kind = detect_docker_kind()
    host_sock = host_ssh_auth_sock()

    mount_dd = False
    mount_host: str | None = None
    ssh_env: str | None = None

    if kind == "desktop" and dd_ssh_sock_is_socket():
        mount_dd = True
        ssh_env = DD_SOCK
        mode = "ssh-agent-desktop"
    elif host_sock:
        mount_host = host_sock
        ssh_env = "/ssh-agent"
        mode = "ssh-agent-host"
    else:
        mode = "https-prefer"

    return host_os, kind, mode, ssh_env, mount_dd, mount_host


def main() -> int:
    host_os, kind, mode, ssh_env, mount_dd, mount_host = decide()
    content = render_overlay(
        host_os=host_os,
        kind=kind,
        mode=mode,
        ssh_auth_sock_env=ssh_env,
        mount_dd=mount_dd,
        mount_host_sock=mount_host,
    )
    OUT_FILE.write_text(content, encoding="utf-8", newline="\n")
    print(
        f"[git-dx-host] wrote {OUT_FILE.name}: "
        f"os={host_os} kind={kind} mode={mode} (optional advanced)"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as exc:  # noqa: BLE001
        stub = render_overlay(
            host_os=detect_host_os(),
            kind="unknown",
            mode="https-prefer",
            ssh_auth_sock_env=None,
            mount_dd=False,
            mount_host_sock=None,
        )
        try:
            OUT_FILE.write_text(stub, encoding="utf-8", newline="\n")
        except OSError:
            pass
        print(f"[git-dx-host] warning: {exc}; wrote HTTPS-prefer stub", file=sys.stderr)
        raise SystemExit(0)
